name: Release

on:
  push:
    branches:
      - main
      - develop
      - fix-*
      - feat-*

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: synclife-api